# Generated by Django 2.1.7 on 2019-05-27 16:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftuser',
            name='active_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 16, 23, 53, 309310, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='giftuser',
            name='building',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='дом'),
        ),
        migrations.AlterField(
            model_name='giftuser',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='населенный пункт'),
        ),
        migrations.AlterField(
            model_name='giftuser',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='название страны'),
        ),
        migrations.AlterField(
            model_name='giftuser',
            name='flat',
            field=models.IntegerField(blank=True, null=True, verbose_name='квартира'),
        ),
        migrations.AlterField(
            model_name='giftuser',
            name='region',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='область'),
        ),
        migrations.AlterField(
            model_name='giftuser',
            name='street',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='улица'),
        ),
    ]
