# Generated by Django 2.1.7 on 2019-05-10 18:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftuser',
            name='address',
        ),
        migrations.AddField(
            model_name='giftuser',
            name='address_list',
            field=models.ManyToManyField(blank=True, related_name='address_list', to='authapp.AddressList'),
        ),
        migrations.AlterField(
            model_name='giftuser',
            name='active_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 27, 18, 59, 4, 960863, tzinfo=utc)),
        ),
    ]
