# Generated by Django 2.1.7 on 2019-05-29 14:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20190529_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftuser',
            name='active_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 16, 14, 54, 35, 13474, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='giftuser',
            name='flat',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='квартира'),
        ),
    ]
