# Generated by Django 2.1.7 on 2019-05-11 16:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20190511_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftuser',
            name='login',
            field=models.CharField(blank=True, max_length=20, verbose_name='логин'),
        ),
        migrations.AlterField(
            model_name='giftuser',
            name='active_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 28, 16, 23, 55, 530075, tzinfo=utc)),
        ),
    ]
