# Generated by Django 2.1.7 on 2019-05-11 17:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20190511_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftuser',
            name='age',
        ),
        migrations.AddField(
            model_name='giftuser',
            name='birhdate',
            field=models.DateField(blank=True, null=True, verbose_name='дата рождения'),
        ),
        migrations.AlterField(
            model_name='giftuser',
            name='active_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 28, 17, 12, 48, 18010, tzinfo=utc)),
        ),
    ]
