# Generated by Django 2.1.7 on 2019-05-26 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20190524_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressname',
            name='name',
            field=models.CharField(max_length=20, verbose_name='название адреса'),
        ),
        migrations.AlterField(
            model_name='giftuser',
            name='active_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 13, 13, 56, 33, 405798, tzinfo=utc)),
        ),
    ]
