# Generated by Django 2.1.7 on 2019-05-26 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_auto_20190526_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='flat',
            field=models.IntegerField(verbose_name='квартира'),
        ),
        migrations.AlterField(
            model_name='giftuser',
            name='active_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 13, 14, 10, 56, 915521, tzinfo=utc)),
        ),
    ]
