# Generated by Django 2.1.7 on 2019-05-26 17:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_auto_20190526_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresslist',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_list_address', to='authapp.Address'),
        ),
        migrations.AlterField(
            model_name='addresslist',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_list_name', to='authapp.AddressName'),
        ),
        migrations.AlterField(
            model_name='giftuser',
            name='active_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 13, 17, 34, 41, 504087, tzinfo=utc)),
        ),
    ]
