# Generated by Django 2.1.7 on 2019-05-27 11:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_auto_20190526_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresslist',
            name='address',
        ),
        migrations.AddField(
            model_name='addresslist',
            name='building',
            field=models.CharField(default=1, max_length=7, verbose_name='дом'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresslist',
            name='city',
            field=models.CharField(default=1, max_length=30, verbose_name='населенный пункт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresslist',
            name='country',
            field=models.CharField(default=1, max_length=30, verbose_name='название страны'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresslist',
            name='flat',
            field=models.IntegerField(default=1, verbose_name='квартира'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresslist',
            name='region',
            field=models.CharField(default=1, max_length=30, verbose_name='область'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresslist',
            name='street',
            field=models.CharField(default=1, max_length=30, verbose_name='улица'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addresslist',
            name='name',
            field=models.CharField(max_length=20, verbose_name='название адреса'),
        ),
        migrations.AlterField(
            model_name='giftuser',
            name='active_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 11, 56, 36, 163564, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='AddressName',
        ),
    ]
