# Generated by Django 2.1.7 on 2019-04-12 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftuser',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='адрес'),
        ),
        migrations.AddField(
            model_name='giftuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='middle_name'),
        ),
        migrations.AlterField(
            model_name='giftuser',
            name='active_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 30, 14, 26, 1, 195679, tzinfo=utc)),
        ),
    ]
