# Generated by Django 2.1.7 on 2019-05-06 10:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftuser',
            name='active_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 23, 10, 37, 3, 440079, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='giftuser',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addressapp.Address'),
        ),
    ]
