# Generated by Django 2.1.7 on 2019-04-26 12:57

import address.models
import authapp.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20190412_1726'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='giftuser',
            managers=[
                ('objects', authapp.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='giftuser',
            name='username',
        ),
        migrations.AddField(
            model_name='giftuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='giftuser',
            name='active_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 13, 12, 57, 27, 784099, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='giftuser',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='address.Address'),
        ),
        migrations.AlterField(
            model_name='giftuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='отчество'),
        ),
    ]
