# Generated by Django 2.1.7 on 2019-05-21 15:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20190521_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftuser',
            name='active_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 8, 15, 42, 41, 539720, tzinfo=utc)),
        ),
    ]
