# Generated by Django 2.1.7 on 2019-05-20 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendsapp', '0002_auto_20190520_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='message',
            field=models.CharField(default='Пользователь хочет добавить вас в друзья!', max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='friendshiprequest',
            unique_together={('from_user', 'to_user')},
        ),
    ]
